### ISSUE TITLE
Ontology versionIRI should be an IRI

### ISSUE THREAD

**Issue by jamesaoverton** [ontoneo-project/Ontoneo#15]
In the current `ontoneo.owl` file the `versionIRI` is 'v1.2'. It would be better for the value to be an IRI (URL) that points to this specific version of the file, and matches the PURL configuration. Most OBO ontologies use a date format such as: http://purl.obolibrary.org/obo/obi/2016-01-01/obi.owl

**Comment by FernandaFarinelli** [comment]
Change from 
        <owl:versionIRI rdf:resource="&obo;ontoneo/releases/v1.0/ontoneo.owl"/>
to
        <owl:versionIRI rdf:resource="&obo;ontoneo/releases/2016-11-07/ontoneo.owl"/>

**Comment by FernandaFarinelli** [comment]
Change from 
        <owl:versionIRI rdf:resource="&obo;ontoneo/releases/v1.1/ontoneo.owl"/>
To
        <owl:versionIRI rdf:resource="&obo;ontoneo/releases/2016-12-14/ontoneo.owl"/>

**Comment by FernandaFarinelli** [comment]
Improvement done.
I already change the yml file.
