### ISSUE TITLE
Ontology uses rdf:comment instead of rdfs:comment

### ISSUE THREAD

**Issue by jvendetti** [ontoneo-project/Ontoneo#20]
There are multiple occurrences in the OWL source file where rdf:comment is used instead of rdfs:comment, e.g., [this line](https://github.com/ontoneo-project/Ontoneo/blob/master/ontoneo.owl#L2870).

This caused an issue with our application (BioPortal), which hosts the ontology at this URL:

http://bioportal.bioontology.org/ontologies/ONTONEO

We were unable to load the ontology into our triplestore with errors like the following:
```
rdf:comment is an unknown RDF namespaced element
```
We modified all occurrences of rdf:comment to rdfs:comment and were able to load the ontology successfully, as detailed in [this issue](https://github.com/ncbo/bioportal-project/issues/50). 

For the moment, we've disabled the functionality that looks for new versions of your ontology at the [designated pull URL](https://raw.githubusercontent.com/ontoneo-project/Ontoneo/master/ontoneo.owl), pending modification of the rdf:comment tags.

**Comment by ontoneo-project** [comment]
Ok
I will check it and update to a new version.

Thanks

**Comment by FernandaFarinelli** [comment]
Sorry for the long period without reply.
I made many updates on Ontoneo and submitted a new version now.
I also submitted a new version of Ontoneo on bioportal.
