### ISSUE TITLE
Possible problems with import statements

### ISSUE THREAD

**Issue by jamesaoverton** [ontoneo-project/Ontoneo#24]
In [`ontoneo.owl`](https://github.com/ontoneo-project/Ontoneo/blob/master/ontoneo.owl) (any probably elsewhere) these imports use uppercase "BFO" and "FMA":

        <owl:imports rdf:resource="http://purl.obolibrary.org/obo/ontoneo/import/BFO_import.owl"/>
        <owl:imports rdf:resource="http://purl.obolibrary.org/obo/ontoneo/import/FMA_import.owl"/>

https://github.com/ontoneo-project/Ontoneo/blob/master/ontoneo.owl#L24-L25

but the actual file names are consistently lowercase: https://github.com/ontoneo-project/Ontoneo/tree/master/import

The names in the imports should exactly match the file names, or the import might fail.

In general, it's best practise for the release version of your ontology to merge together all imports, so there are no `owl:imports` left to cause problems.

**Comment by FernandaFarinelli** [comment]
I did it and I'll publish a new version soon.
